package com.pa2.milk.api.model.enums;

public enum EnumAnalisesSolicitadas {
	COMPOSICAO, CASEINA, PONTO_CRIOSCOPICO, CELULAS_SOMATICAS,
	NITROGENIO_UREICO, CONDUTIVIDADE_ELETRICA, RESIDUO_ANTIBIOTICO,
	PH, ACIDEZ_DORNIC, DENSIDADE_RELATIVA, CBT, FORMOL,
	ACUCARES, ALCALINIZANTES,LACTOPEROXIDASE,
    PEROXIDO_HIDROGENIO, CLORETOS, AMIDO
	
	
//	COMPOSICAO, CASEINA, PONTO_CRIOSCOPICO, CELULAS_SOMATICAS,
//	NITROGENIO_UREICO, CONDUTIVIDADE_ELETRICA, RESIDUO_ANTIBIOTICO,
//	PH, SORO, ACIDO_DORNIC, DENSIDADE_RELATIVA, CBT, ANALISES_FRAUDE_FORMOL,
//	ANALISES_FRAUDE_ACUCARES, ANALISES_FRAUDE_ALCALINIZANTES, ANALISES_FRAUDE_LACTOPEROXIDADE,
//	ANALISES_FRAUDE_PEROXIDO_HIDROGENIO, ANALISES_FRAUDE_CLORETOS, ANALISES_FRAUDE_AMIDO

  


}

